# Generated by Django 5.2 on 2025-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Park",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(null=True)),
                ("category", models.CharField(max_length=100, null=True)),
                ("status", models.CharField(max_length=50, null=True)),
                ("full_address", models.CharField(max_length=512, null=True)),
                ("street", models.CharField(max_length=255, null=True)),
                ("lat", models.FloatField(null=True)),
                ("lon", models.FloatField(null=True)),
            ],
            options={
                "db_table": "park",
            },
        ),
    ]
